name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          cd C && make clean && make && cd ..

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: display-binary
          path: display-binary

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: display-binary

      - name: Set Version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "PKG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "PKG_VERSION=1.0.0" >> $GITHUB_ENV
          fi

      - name: Create rpm package
        id: nfpm-rpm
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          packager: rpm
          target: display-u6143.rpm

      - name: Create deb package
        id: nfpm-deb
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          packager: deb
          target: display-u6143.deb

      - name: Create apk package
        id: nfpm-apk
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          packager: apk
          target: display-u6143.apk

      - name: Create GitHub Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          body: |
            This release includes:
            - `.deb` package for ARM64
            - `.rpm` package for ARM64
            - `.apk` package for Alpine Linux (aarch64)
            - Raw binary for ARM64
          draft: false
          prerelease: false
          gzip: folders
          files: >
            display-u6143.deb
            display-u6143.rpm
            display-u6143.apk
            display-binary
